apiVersion: v1
kind: Service
metadata:
  name: terraform-applier
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: terraform-applier
