apiVersion: v1
kind: Service
metadata:
  name: terraform-applier
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.54
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: terraform-applier
