apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager.yaml
  - alertmanager-ingress.yaml
  - alertmanager-service.yaml

configMapGenerator:
  - name: alertmanager-config
    files:
      - resources/config.yaml
  - name: alertmanager-template
    files:
      - resources/template.tmpl

secretGenerator:
  - name: slack
    files:
      - secrets/slack
