apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sandbox
spec:
  interval: 1m
  targetNamespace: sandbox
  path: ./kubernetes-manifests/sandbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
