apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - homer.yaml
  - homer-ingress.yaml
  - homer-service.yaml

configMapGenerator:
- name: homer-config
  files:
  - resources/config.yml
