{
 "title": "Kubernetes - pod resources",
 "description": "Shows resource usage of Kubernetes pods.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(sum(rate(container_cpu_usage_seconds_total[1h])) by (instance))"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\"}, label_app)"
    }
   },
   {
    "name": "app_kubernetes_io_name",
    "label": "app_kubernetes_io_name",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\"}, label_app_kubernetes_io_name)"
    }
   },
   { "name": "app_kubernetes_io_instance", "label": "pod_name_pattern", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "all pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Working Set",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{pod!=\"\",image!=\"\",instance=~\"^$instance$\"}, \"node\", \"$1\", \"instance\", \"(.+)\")) / sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\",node=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(rate(container_cpu_usage_seconds_total{pod!=\"\",image!=\"\",instance=~\"^$instance$\"}[5m]), \"node\", \"$1\", \"instance\", \"(.+)\")) / sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\",node=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Root Filesystem Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_summary_container_logs_used_bytes{instance=~\"^$instance$\"} + kube_summary_container_rootfs_used_bytes{instance=~\"^$instance$\"}) / sum(kube_node_status_capacity{unit=\"byte\",resource=\"ephemeral_storage\",node=~\"^$instance$\"})) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod!=\"\",image!=\"\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\",unit=\"byte\",node=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\",image!=\"\",instance=~\"^$instance$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",unit=\"core\",node=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_summary_container_logs_used_bytes{instance=~\"^$instance$\"} + kube_summary_container_rootfs_used_bytes{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"ephemeral_storage\",node=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[5m]))"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "each pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",instance=~\"^$instance$\",namespace=~\"^$namespace$\", pod=~\"$app-.+\", pod=~\"$app_kubernetes_io_name-.+\", pod=~\"$app_kubernetes_io_instance-.+\"}[5m])) by (pod,namespace)"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",instance=~\"^$instance$\",namespace=~\"^$namespace$\", pod=~\"$app-.+\", pod=~\"$app_kubernetes_io_name-.+\", pod=~\"$app_kubernetes_io_instance-.+\"}) by (pod,namespace)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\",instance=~\"^$instance$\",namespace=~\"^$namespace$\", pod=~\"$app-.+\", pod=~\"$app_kubernetes_io_name-.+\", pod=~\"$app_kubernetes_io_instance-.+\"}[5m])) by (pod,namespace)"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\",instance=~\"^$instance$\",namespace=~\"^$namespace$\", pod=~\"$app-.+\", pod=~\"$app_kubernetes_io_name-.+\", pod=~\"$app_kubernetes_io_instance-.+\"}[5m])) by (pod,namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem: rootfs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_summary_container_rootfs_used_bytes{instance=~\"^$instance$\",namespace=~\"^$namespace$\", pod=~\"$app-.+\", pod=~\"$app_kubernetes_io_name-.+\", pod=~\"$app_kubernetes_io_instance-.+\"}) by (pod,namespace)"
    }
   ]
  },
  {
   "title": "Filesystem: logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_summary_container_logs_used_bytes{instance=~\"^$instance$\",namespace=~\"^$namespace$\", pod=~\"$app-.+\", pod=~\"$app_kubernetes_io_name-.+\", pod=~\"$app_kubernetes_io_instance-.+\"}) by (pod,namespace)"
    }
   ]
  }
 ]
}