resource "talos_machine_secrets" "this" {}

data "talos_client_configuration" "this" {
  cluster_name         = var.cluster.name
  client_configuration = talos_machine_secrets.this.client_configuration
  nodes                = [for node in var.cluster.nodes : node.ipv4.address]
  endpoints            = [for node in var.cluster.nodes : node.ipv4.address if node.type == "controlplane"]
}

# The node machine configs are owned by talhelper (talos/clusterconfig/*.yaml),
# generated by `make genconfig`. Terraform only applies them during bootstrap
# and for the initial cluster join; the configs are MAC-matched and idempotent,
# so re-applies never overwrite hostnames or static IPs.
resource "talos_machine_configuration_apply" "this" {
  depends_on                  = [proxmox_virtual_environment_vm.this]
  for_each                    = var.cluster.nodes
  client_configuration        = talos_machine_secrets.this.client_configuration
  machine_configuration_input = file("../../../talos/clusterconfig/homelab-${each.key}.yaml")
  node                        = each.value.ipv4.address
}

resource "talos_machine_bootstrap" "this" {
  depends_on           = [talos_machine_configuration_apply.this]
  client_configuration = talos_machine_secrets.this.client_configuration
  node                 = data.talos_client_configuration.this.endpoints[0]
}

data "talos_cluster_health" "this" {
  depends_on           = [talos_machine_configuration_apply.this, talos_machine_bootstrap.this]
  client_configuration = data.talos_client_configuration.this.client_configuration
  control_plane_nodes  = [for node in var.cluster.nodes : node.ipv4.address if node.type == "controlplane"]
  worker_nodes         = [for node in var.cluster.nodes : node.ipv4.address if node.type == "worker"]
  endpoints            = data.talos_client_configuration.this.endpoints
  timeouts = {
    read = "10m"
  }
}

resource "talos_cluster_kubeconfig" "this" {
  depends_on           = [talos_machine_bootstrap.this, data.talos_cluster_health.this]
  client_configuration = talos_machine_secrets.this.client_configuration
  node                 = data.talos_client_configuration.this.endpoints[0]
  endpoint             = data.talos_client_configuration.this.endpoints[0]
  timeouts = {
    read = "1m"
  }
}

output "talosconfig" {
  value     = data.talos_client_configuration.this.talos_config
  sensitive = true
}

output "kubeconfig" {
  value     = resource.talos_cluster_kubeconfig.this.kubeconfig_raw
  sensitive = true
}
