apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - prometheus-clusterrole.yaml
  - prometheus-ingress.yaml
  - prometheus-service.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - resources/config.yaml
  - name: prometheus-rules
    files:
      - resources/kube-nodes.yaml
      - resources/kube-storage.yaml
      - resources/proxmox.yaml
