apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus.yaml
  - prometheus-clusterrole.yaml
  - prometheus-service.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - resources/config.yaml
    # options:
    #   disableNameSuffixHash: true
  - name: prometheus-rules
    files:
      - resources/rules.yaml
    # options:
    #   disableNameSuffixHash: true
#
# secretGenerator:
#   - name: grafana-admin
#     envs:
#       - secrets/grafana-admin
#     options:
#       disableNameSuffixHash: true
