apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    app: prometheus
  annotations:
    {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: prometheus
