apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
spec:
  project: main
  source:
    repoURL: git@github.com:DTLP/homelab.git
    targetRevision: main
    path: kubernetes-manifests/nfs-provisioner
  destination:
    name: in-cluster
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
