apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - loki-role.yaml
  # - loki-secret.yaml
  - loki-service.yaml
  - loki-statefulset.yaml

configMapGenerator:
  - name: loki
    files:
      - resources/loki.yaml
    options:
      disableNameSuffixHash: true
