apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: loki
  annotations:
    {}
  name: loki
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
    prometheus.io/path: "/metrics"
  labels:
    app.kubernetes.io/name: loki
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: loki
