apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - promtail-clusterrole.yaml
  - promtail-daemonset.yaml
  - promtail-service.yaml

configMapGenerator:
  - name: promtail
    files:
      - resources/promtail.yaml
    options:
      disableNameSuffixHash: true
