apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-clusterrole.yaml
  - grafana-configmap.yaml
  - grafana-sts.yaml
  - grafana-role.yaml
  - grafana-service.yaml
  - terraform-modules/

configMapGenerator:
  - name: grafana-datasources
    files:
      - resources/datasources.yaml

secretGenerator:
  - name: grafana
    envs:
      - secrets/grafana
    options:
      disableNameSuffixHash: true
