apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-volume.yaml

configMapGenerator:
  - name: grafana
    files:
      - datasources.yaml=resources/datasources.yaml
      - dashboards.yaml=resources/dashboards.yaml
