apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-clusterrole.yaml
  - grafana-configmap.yaml
  - grafana-deployment.yaml
  - grafana-role.yaml
  - grafana-service.yaml

secretGenerator:
  - name: grafana-admin
    envs:
      - secrets/grafana-admin
    options:
      disableNameSuffixHash: true
