apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cadvisor-deployment.yaml
  - cadvisor-service.yaml
  - node-exporter.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
