apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - 10.0.0.10:9100 # master-0
              - 10.0.0.11:9100 # master-1
              - 10.0.0.20:9100 # worker-0
              - 10.0.0.21:9100 # worker-1
              - 10.0.0.22:9100 # worker-2
