apiVersion: batch/v1
kind: CronJob
metadata:
  name: popeye
spec:
  schedule: "* 10 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: popeye
          restartPolicy: Never
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: popeye
              image: derailed/popeye
              args:
                - --all-namespaces
                - --push-gtwy-url=http://pushgateway.monitoring.svc.cluster.local:9091
                - --force-exit-zero
              resources:
                limits:
                  cpu:    500m
                  memory: 500Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                runAsNonRoot: true
