---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cainjector
  labels:
    app.kubernetes.io/name: cainjector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook
  labels:
    app.kubernetes.io/name: webhook
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-cainjector
  labels:
    app.kubernetes.io/name: cainjector
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9402
    name: http-metrics
  selector:
    app.kubernetes.io/name: cainjector
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9402
    name: tcp-prometheus-servicemonitor
    targetPort: 9402
  selector:
    app.kubernetes.io/name: cert-manager
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  labels:
    app.kubernetes.io/name: webhook
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: "https"
  - name: metrics
    port: 9402
    protocol: TCP
    targetPort: "http-metrics"
  selector:
    app.kubernetes.io/name: webhook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-startupapicheck
  labels:
    app.kubernetes.io/name: startupapicheck
