apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: dmitry.lapo@hotmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: dmitry.lapo@hotmail.com
            apiTokenSecretRef:
              name: cloudflare
              key: api-token
        selector:
          dnsZones:
            - "dtlp.cc"