apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - cert-manager-cainjector.yaml
  - cert-manager-rbac.yaml
  - cert-manager-services.yaml
  - cert-manager-webhook.yaml
  - cluster-issuer.yaml

secretGenerator:
  - name: cloudflare
    envs:
      - secrets/cloudflare
    options:
      disableNameSuffixHash: true
