apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pve-exporter.yaml
  - pve-exporter-service.yaml

secretGenerator:
  - name: pve-exporter
    files:
      - pve.yml=secrets/pve.yaml
