apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /pve
    prometheus.io/port: "9221"
  name: pve-exporter
  labels:
    app: pve-exporter
spec:
  type: ClusterIP
  ports:
    - name: pve-exporter
      port: 9221
      targetPort: 9221
  selector:
    app: pve-exporter
