apiVersion: apps/v1
kind: Deployment
metadata:
  name: pve-exporter
  labels:
    app: pve-exporter
spec:
  selector:
    matchLabels:
      app: pve-exporter
  template:
    metadata:
      labels:
        app: pve-exporter
    spec:
      containers:
        - name: pve-exporter
          image: prompve/prometheus-pve-exporter:3.5.2
          ports:
            - name: pve-exporter
              containerPort: 9221
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/
          resources:
            limits:
              memory: 100M
      volumes:
        - name: config
          secret:
            secretName: pve-exporter
