global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/template.tmpl'

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: alerts
    api_url_file: /etc/secrets/slack
    title: '{{ template "title" . }}'
    text: '{{ template "body" . }}'
    send_resolved: true
