apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
spec:
  project: main
  source:
    repoURL: git@github.com:DTLP/homelab.git
    targetRevision: main
    path: kubernetes-manifests/kafka
  destination:
    name: in-cluster
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
