apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/fluxcd/flux2/manifests/bases/source-controller?ref=v2.5.1
  - https://github.com/fluxcd/flux2/manifests/bases/kustomize-controller?ref=v2.5.1
  - https://github.com/fluxcd/flux2/manifests/rbac?ref=v2.5.1
  - https://github.com/fluxcd/flux2/manifests/policies?ref=v2.5.1

  - git-repos.yaml
