clusterName: homelab
endpoint: https://192.168.0.39:6443

talosVersion: ${TALOS_VERSION}

domain: cluster.local

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12

nodes:
  - hostname: master-0
    ipAddress: 192.168.0.30
    controlPlane: true
    installDisk: /dev/sda

  - hostname: master-1
    ipAddress: 192.168.0.31
    controlPlane: true
    installDisk: /dev/sda

  - hostname: master-2
    ipAddress: 192.168.0.32
    controlPlane: true
    installDisk: /dev/sda

  - hostname: worker-0
    ipAddress: 192.168.0.40
    controlPlane: false
    installDisk: /dev/sda

  - hostname: worker-1
    ipAddress: 192.168.0.41
    controlPlane: false
    installDisk: /dev/sda

  - hostname: worker-2
    installDisk: /dev/sda
    ipAddress: 192.168.0.42
    controlPlane: false

  - hostname: worker-3
    ipAddress: 192.168.0.43
    controlPlane: false
    installDisk: /dev/sda

controlPlane:
  patches:
    - patches/vip.yaml
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent
