apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app: node-exporter
