apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
    prometheus.io/path: "/metrics"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.56
  ports:
    - name: metrics
      port: 8083
      targetPort: 8083
