# reference: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/project.yaml

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: main project
  sourceRepos:
    - git@github.com:DTLP/homelab.git

  sourceNamespaces:
    - argocd
    - certs
    - flux-system
    - ingress-controller
    - kafka
    - kube-system
    - metallb-system
    - monitoring
    - nfs-provisioner
    - terraform-applier

  destinations:
    - namespace: argocd
      name: in-cluster
    - namespace: certs
      name: in-cluster
    - namespace: flux-system
      name: in-cluster
    - namespace: ingress-controller
      name: in-cluster
    - namespace: kafka
      name: in-cluster
    - namespace: kube-system
      name: in-cluster
    - namespace: metallb-system
      name: in-cluster
    - namespace: monitoring
      name: in-cluster
    - namespace: nfs-provisioner
      name: in-cluster
    - namespace: terraform-applier
      name: in-cluster
