apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: main
  source:
    repoURL: git@github.com:DTLP/homelab.git
    targetRevision: main
    path: kubernetes-manifests/argocd
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    automated: 
      prune: true
      selfHeal: true
