apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-app.yaml
  - argocd-ingress.yaml
  - argocd-project.yaml

  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - path: argocd-cmd-params-cm-patch.yaml
  - path: argocd-server-svc-patch.yaml

secretGenerator:
  - files:
      - sshPrivateKey=secrets/github-ssh-key
    literals:
      - url=git@github.com:DTLP/homelab.git
      - project=default
      - type=git
    name: homelab-repo
    options:
      disableNameSuffixHash: true
      labels:
        argocd.argoproj.io/secret-type: repository
