apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certs
spec:
  project: main
  source:
    repoURL: git@github.com:DTLP/homelab.git
    targetRevision: main
    path: kubernetes-manifests/certs
  destination:
    name: in-cluster
    namespace: certs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
