apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dtlp-cc-wildcard
spec:
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: dtlp-cc-wildcard-cert
  commonName: "*.dtlp.cc"
  dnsNames:
    - "*.dtlp.cc"
