---
- name: Configure SSH key-based authentication on Proxmox cluster
  hosts: pve_nodes
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_pass: "{{ lookup('file', 'secrets/root_password') }}"
    ssh_priv_key_path: "secrets/id_ed25519"
    ssh_pub_key_path: "secrets/id_ed25519.pub"

  tasks:
    - name: Replace /root/.ssh/id_rsa with the private SSH key
      copy:
        src: "{{ ssh_priv_key_path }}"
        dest: /root/.ssh/id_ed25519
        owner: root
        group: root
        mode: '0600'

    - name: Replace the content of /etc/pve/priv/authorized_keys with the public SSH key
      copy:
        src: "{{ ssh_pub_key_path }}"
        dest: /etc/pve/priv/authorized_keys
        owner: root
        group: www-data
        mode: '0600'

    - name: Disable password authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Disable PermitRootLogin with password
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin without-password'
        state: present

    - name: Restart SSH service to apply changes
      service:
        name: sshd
        state: restarted
