---
- name: Download Ubuntu Cloud image
  hosts: pve3
  become: yes

  tasks:
    - name: Ensure the directory exists
      file:
        path: /mnt/pve/{{ vm_disk }}/template/iso/
        state: directory
        mode: '0755'

    - name: Download the Ubuntu Cloud image
      get_url:
        url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
        dest: /mnt/pve/{{ vm_disk }}/template/iso/noble-server-cloudimg-amd64.img
        mode: '0644'

- name: Distribue Ubuntu Cloud image to other nodes
  hosts: pve_nodes
  become: yes

  tasks:
    - name: Ensure the directory exists
      file:
        path: /mnt/pve/{{ vm_disk }}/template/iso/
        state: directory
        mode: '0755'

    - name: Copy the Ubuntu Cloud image to other nodes
      synchronize:
        src: /mnt/pve/{{ vm_disk }}/template/iso/noble-server-cloudimg-amd64.img
        dest: /mnt/pve/{{ vm_disk }}/template/iso/noble-server-cloudimg-amd64.img
        mode: push
        rsync_opts:
          - "--rsync-path=rsync"
      delegate_to: pve3
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: /root/.ssh/id_ed25519
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

- name: Setup Ubuntu Cloud VM on Proxmox
  hosts: pve_nodes
  become: yes

  tasks:
    - name: Create the VM
      command: qm create 800{{ id }} --memory 6144 --core 3 --name ubuntu-cloud --net0 virtio,bridge=vmbr0

    - name: Import the disk
      command: qm importdisk 800{{ id }} /mnt/pve/{{ vm_disk }}/template/iso/noble-server-cloudimg-amd64.img {{ vm_disk }}

    - name: Set SCSI hardware and attach disk
      command: qm set 800{{ id }} --scsihw virtio-scsi-pci --scsi0 {{ vm_disk }}:800{{ id }}/vm-800{{ id }}-disk-0.raw

    - name: Set cloud-init disk
      command: qm set 800{{ id }} --ide2 {{ vm_disk }}:cloudinit

    - name: Configure the boot options
      command: qm set 800{{ id }} --boot c --bootdisk scsi0

    - name: Set serial0 to socket and VGA to serial0
      command: qm set 800{{ id }} --serial0 socket --vga serial0
