# Kyverno upstream deployment config excludes kube-system resources by default.
# Since we deploy a lot of things under kube-system, let's not exclude it
# blindly, but cater for kube-system resources in our policies.
apiVersion: v1
kind: ConfigMap
metadata:
  name: kyverno
  namespace: kyverno
data:
  enableDefaultRegistryMutation: "true"
  defaultRegistry: "docker.io"
  generateSuccessEvents: "false"
  excludeGroups: "system:nodes"
  resourceFilters: >-
    [*/*,kube-system,*]
    [Event,*,*]
    [*/*,kube-public,*]
    [*/*,kube-node-lease,*]
    [Node,*,*]
    [Node/*,*,*]
    [APIService,*,*]
    [APIService/*,*,*]
    [TokenReview,*,*]
    [SubjectAccessReview,*,*]
    [SelfSubjectAccessReview,*,*]
    [Binding,*,*]
    [Pod/binding,*,*]
    [ReplicaSet,*,*]
    [ReplicaSet/*,*,*]
    [EphemeralReport,*,*]
    [ClusterEphemeralReport,*,*]
    [ClusterRole,*,kyverno:admission-controller]
    [ClusterRole,*,kyverno:admission-controller:core]
    [ClusterRole,*,kyverno:admission-controller:additional]
    [ClusterRole,*,kyverno:background-controller]
    [ClusterRole,*,kyverno:background-controller:core]
    [ClusterRole,*,kyverno:background-controller:additional]
    [ClusterRole,*,kyverno:cleanup-controller]
    [ClusterRole,*,kyverno:cleanup-controller:core]
    [ClusterRole,*,kyverno:cleanup-controller:additional]
    [ClusterRole,*,kyverno:reports-controller]
    [ClusterRole,*,kyverno:reports-controller:core]
    [ClusterRole,*,kyverno:reports-controller:additional]
    [ClusterRoleBinding,*,kyverno:admission-controller]
    [ClusterRoleBinding,*,kyverno:background-controller]
    [ClusterRoleBinding,*,kyverno:cleanup-controller]
    [ClusterRoleBinding,*,kyverno:reports-controller]
    [ServiceAccount,kube-system,kyverno-admission-controller]
    [ServiceAccount/*,kube-system,kyverno-admission-controller]
    [ServiceAccount,kube-system,kyverno-background-controller]
    [ServiceAccount/*,kube-system,kyverno-background-controller]
    [ServiceAccount,kube-system,kyverno-cleanup-controller]
    [ServiceAccount/*,kube-system,kyverno-cleanup-controller]
    [ServiceAccount,kube-system,kyverno-reports-controller]
    [ServiceAccount/*,kube-system,kyverno-reports-controller]
    [Role,kube-system,kyverno:admission-controller]
    [Role,kube-system,kyverno:background-controller]
    [Role,kube-system,kyverno:cleanup-controller]
    [Role,kube-system,kyverno:reports-controller]
    [RoleBinding,kube-system,kyverno:admission-controller]
    [RoleBinding,kube-system,kyverno:background-controller]
    [RoleBinding,kube-system,kyverno:cleanup-controller]
    [RoleBinding,kube-system,kyverno:reports-controller]
    [ConfigMap,kube-system,kyverno]
    [ConfigMap,kube-system,kyverno-metrics]
    [Deployment,kube-system,kyverno-admission-controller]
    [Deployment/*,kube-system,kyverno-admission-controller]
    [Deployment,kube-system,kyverno-background-controller]
    [Deployment/*,kube-system,kyverno-background-controller]
    [Deployment,kube-system,kyverno-cleanup-controller]
    [Deployment/*,kube-system,kyverno-cleanup-controller]
    [Deployment,kube-system,kyverno-reports-controller]
    [Deployment/*,kube-system,kyverno-reports-controller]
    [Pod,kube-system,kyverno-admission-controller-*]
    [Pod/*,kube-system,kyverno-admission-controller-*]
    [Pod,kube-system,kyverno-background-controller-*]
    [Pod/*,kube-system,kyverno-background-controller-*]
    [Pod,kube-system,kyverno-cleanup-controller-*]
    [Pod/*,kube-system,kyverno-cleanup-controller-*]
    [Pod,kube-system,kyverno-reports-controller-*]
    [Pod/*,kube-system,kyverno-reports-controller-*]
    [Job,kube-system,kyverno-hook-pre-delete]
    [Job/*,kube-system,kyverno-hook-pre-delete]
    [NetworkPolicy,kube-system,kyverno-admission-controller]
    [NetworkPolicy/*,kube-system,kyverno-admission-controller]
    [NetworkPolicy,kube-system,kyverno-background-controller]
    [NetworkPolicy/*,kube-system,kyverno-background-controller]
    [NetworkPolicy,kube-system,kyverno-cleanup-controller]
    [NetworkPolicy/*,kube-system,kyverno-cleanup-controller]
    [NetworkPolicy,kube-system,kyverno-reports-controller]
    [NetworkPolicy/*,kube-system,kyverno-reports-controller]
    [PodDisruptionBudget,kube-system,kyverno-admission-controller]
    [PodDisruptionBudget/*,kube-system,kyverno-admission-controller]
    [PodDisruptionBudget,kube-system,kyverno-background-controller]
    [PodDisruptionBudget/*,kube-system,kyverno-background-controller]
    [PodDisruptionBudget,kube-system,kyverno-cleanup-controller]
    [PodDisruptionBudget/*,kube-system,kyverno-cleanup-controller]
    [PodDisruptionBudget,kube-system,kyverno-reports-controller]
    [PodDisruptionBudget/*,kube-system,kyverno-reports-controller]
    [Service,kube-system,kyverno-svc]
    [Service/*,kube-system,kyverno-svc]
    [Service,kube-system,kyverno-svc-metrics]
    [Service/*,kube-system,kyverno-svc-metrics]
    [Service,kube-system,kyverno-background-controller-metrics]
    [Service/*,kube-system,kyverno-background-controller-metrics]
    [Service,kube-system,kyverno-cleanup-controller]
    [Service/*,kube-system,kyverno-cleanup-controller]
    [Service,kube-system,kyverno-cleanup-controller-metrics]
    [Service/*,kube-system,kyverno-cleanup-controller-metrics]
    [Service,kube-system,kyverno-reports-controller-metrics]
    [Service/*,kube-system,kyverno-reports-controller-metrics]
    [ServiceMonitor,kube-system,kyverno-admission-controller]
    [ServiceMonitor,kube-system,kyverno-background-controller]
    [ServiceMonitor,kube-system,kyverno-cleanup-controller]
    [ServiceMonitor,kube-system,kyverno-reports-controller]
    [Secret,kube-system,kyverno-svc.kyverno.svc.*]
    [Secret,kube-system,kyverno-cleanup-controller.kyverno.svc.*]
  updateRequestThreshold: "1000"
  webhooks: "{\"namespaceSelector\":{\"matchExpressions\":[{\"key\":\"kubernetes.io/metadata.name\",\"operator\":\"NotIn\",\"values\":[\"kyverno\"]}],\"matchLabels\":null}}"
  webhookAnnotations: "{\"admissions.enforcer/disabled\":\"true\"}"
