apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - influxdb-sts.yaml
  - influxdb-service.yaml

configMapGenerator:
  - name: influxdb-config
    files:
      - resources/influxdb.conf

secretGenerator:
  - name: influxdb
    envs:
      - secrets/credentials
    options:
      disableNameSuffixHash: true
