apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: talos
spec:
  interval: 1m
  targetNamespace: talos
  path: ./kubernetes-manifests/talos
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
