apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  labels:
    app.kubernetes.io/name: pushgateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pushgateway
    spec:
      serviceAccountName: pushgateway
      containers:
        - name: pushgateway
          image: "quay.io/prometheus/pushgateway:v1.11.1"
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: storage
              mountPath: "/data"
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: storage
          emptyDir: {}
