groups:
- name: proxmox
  rules:
  - alert: NodeDown
    # match nodes only. do not match lxc and qemu
    expr: pve_up{id=~"node/(.*)"} != 1
    for: 10m
    labels:
      instance: "{{ $labels.id }}"
    annotations:
      summary: "Proxmox Node is unavailable"
      description: "A {{ $labels.id }} proxmox node appears to be down."
      impact: "Performance degradation and potential service interruption."
      action: "Investigate the node and reboot if necessary."
      dashboard: http://grafana.dtlp.cc/d/Dp7Cd57Zza
  - alert: HighCPUUsage
    # match nodes only. do not match lxc and qemu
    expr: (pve_cpu_usage_ratio{id=~"node/(.*)"} / pve_cpu_usage_limit{id=~"node/(.*)"}) * 100 > 80
    for: 10m
    labels:
      instance: "{{ $labels.id }}"
    annotations:
      summary: "High CPU Usage on Proxmox Node"
      description: "CPU usage is above 80% for more than 10 minutes on node {{ $labels.id }}."
      impact: "Performance degradation and potential service interruption."
      action: "Investigate CPU consumption."
      dashboard: http://grafana.dtlp.cc/d/Dp7Cd57Zza
  - alert: HighMemoryUsage
    # match nodes only. do not match lxc and qemu
    expr: (pve_memory_usage_bytes{id=~"node/(.*)"} / pve_memory_size_bytes{id=~"node/(.*)"}) * 100 > 90
    for: 10m
    labels:
      instance: "{{ $labels.id }}"
    annotations:
      summary: "High Memory Usage on Proxmox Node"
      description: "Memory usage is above 90% for more than 10 minutes on node {{ $labels.id }}."
      impact: "Performance degradation and potential service interruption."
      action: "Investigate memory consumption."
      dashboard: http://grafana.dtlp.cc/d/Dp7Cd57Zza
  - alert: HighStorageUsage
    # match nodes only. do not match lxc and qemu
    expr: (pve_disk_usage_bytes{id=~"storage/pve\\d+/(.*)"} / pve_disk_size_bytes{id=~"storage/pve\\d+/(.*)"}) * 100 > 80
    for: 10m
    labels:
      instance: "{{ $labels.id }}"
    annotations:
      summary: "High Storage Usage on Proxmox Node"
      description: "Storage usage is above 80% for more than 10 minutes on node {{ $labels.id }}."
      impact: "Potential service interruption or data loss."
      action: "Review and clean up unnecessary files and monitor for further usage trends."
      dashboard: http://grafana.dtlp.cc/d/Dp7Cd57Zza
