groups:
- name: TEST high pod memory
  rules:
  - alert: High Pod Memory
    expr: sum(container_memory_usage_bytes) > 1
    for: 1m
    labels:
      severity: slack
    annotations:
      summary: High Memory Usage
  - name: TEST high cpu usage
    rules:
      - alert: HighCPUUsage
        expr: sum(rate(cpu_usage_seconds_total[5m])) by (instance) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes."
