#cloud-config

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

users:
  - name: "root"
    hashed_passwd: "${root_password}"
    lock_passwd: false
    groups: [ sudo ]
    shell: "/bin/bash"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - ${admin_ssh_key}

runcmd:
  - systemctl start qemu-guest-agent
  - hostnamectl set-hostname ${hostname}
  - reboot
