#cloud-config

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - docker.io

write_files:
  - path: /etc/docker/daemon.json
    permissions: '0644'
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
  - path: /root/.ssh/id_ed25519
    permissions: '0600'
    content: |
      ${replace(root_ssh_key, "\n", "\n      ")}
  - path: /etc/crictl.yaml
    content: |
      runtime-endpoint: "unix:///run/containerd/containerd.sock"
      image-endpoint: "unix:///run/containerd/containerd.sock"
    permissions: '0644'
  - path: /etc/containerd/config.toml
    content: |
      version = 2
      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
        [plugins."io.containerd.grpc.v1.cri".containerd]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true
    permissions: '0644'

users:
  - name: "root"
    hashed_passwd: "${root_password}"
    lock_passwd: false
    groups: [ sudo ]
    shell: "/bin/bash"
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - ${admin_ssh_key}

runcmd:
  - hostnamectl set-hostname ${hostname}
  - systemctl start qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  - mkdir -p -m 755 /etc/apt/keyrings
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl
  - curl -L https://github.com/projectcalico/calico/releases/download/v3.29.1/calicoctl-linux-amd64 -o /usr/local/bin/calicoctl
  - chmod +x /usr/local/bin/calicoctl
  - scp -o StrictHostKeyChecking=no -i /root/.ssh/id_ed25519 root@${k8s_master_node_ip}:/joincluster.sh /joincluster.sh
  - until [ -f /joincluster.sh ]; do sleep 1; done
  - bash /joincluster.sh
  - mkdir -p /root/.kube
  - cp /etc/kubernetes/kubelet.conf /root/.kube/config
  - reboot
