apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
---
apiVersion: v1
kind: Namespace
metadata:
  name: sys-argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: sys-mon
---
apiVersion: v1
kind: Namespace
metadata:
  name: sys-prom
