apiVersion: 1
datasources:
  - name: Alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    access: proxy
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: true
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
