apiVersion: 1
datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: true
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    jsonData:
      version: Flux
      organization: homelab
      defaultBucket: proxmox
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_API_TOKEN}
